Listen = "0.0.0.0:5678"
ProxyURL = ""
MysqlDns = "root:12345678@tcp(geekai-mysql:3306)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "/static"
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  MaxAge = 86400

[AdminSession]
  SecretKey = "wr1uzwz2meai4z9j0e0tsyf6x523ui6zpnyaim4x2x37meakv13349llqpipyk40"
  MaxAge = 8640000

[Redis]
  Host = "geekai-redis"
  Port = 6379
  Password = "12345678"
  DB = 0

[ApiConfig]
  ApiURL = "http://service.r9it.com:9001"
  AppId = ""
  Token = ""

[SMS]
  Active = "Ali"
  [SMS.Ali]
    AccessKey = ""
    AccessSecret = ""
    Product = "Dysmsapi"
    Domain = "dysmsapi.aliyuncs.com"
    Sign = ""
    CodeTempId = ""
  [SMS.Bao]
    Username = ""
    Password = ""
    Domain = "api.smsbao.com"
    Sign = "【talkme】"
    CodeTemplate = "您的验证码是{code}。5分钟有效，若非本人操作，请忽略本短信。"

[OSS]
  Active = "Local"
  [OSS.Local]
    BasePath = "./static/upload"
    BaseURL = "/static/upload"
  [OSS.Minio]
    Endpoint = ""
    AccessKey = ""
    AccessSecret = ""
    Bucket = "geekai"
    SubDir = ""
    UseSSL = false
    Domain = ""
  [OSS.QiNiu]
    Zone = "z2"
    AccessKey = ""
    AccessSecret = ""
    Bucket = ""
    SubDir = ""
    Domain = ""
  [OSS.AliYun]
    Endpoint = "oss-cn-hangzhou.aliyuncs.com"
    AccessKey = ""
    AccessSecret = ""
    Bucket = "geekai"
    SubDir = ""
    Domain = ""

[[MjProxyConfigs]]
  Enabled = false
  ApiURL = "http://geekai-midjourney-proxy:8082"
  Mode = ""
  ApiKey = "sk-geekmaster"

[[MjPlusConfigs]]
  Enabled = false
  ApiURL = "https://api.chat-plus.net"
  Mode = "fast"
  ApiKey = "sk-xxx"

[[SdConfigs]]
  Enabled = false
  Model = ""
  ApiURL = ""
  ApiKey = ""

[XXLConfig]   # xxl-job 配置，需要你部署 XXL-JOB 定时任务工具，用来定期清理未支付订单和清理过期 VIP，如果你没有启用支付服务，则该服务也无需启动
  Enabled = true  # 是否启用 XXL JOB 服务
  ServerAddr = "http://geekai-xxl-job-admin:8080/xxl-job-admin"  # xxl-job-admin 管理地址
  ExecutorIp = "geekai-api"  # 执行器 IP 地址
  ExecutorPort = "9999" # 执行器服务端口
  AccessToken = "GeekMaster"  # 执行器 API 通信 token
  RegistryKey = "chatgpt-plus"  # 任务注册 key，需要与 xxl-job 管理后台配置一致，请不要随意改动

[AlipayConfig]
  Enabled = false
  SandBox = false
  AppId = "9021000131658023"
  UserId = "2088721020750581"
  PrivateKey = "certs/alipay/privateKey.txt"
  PublicKey = "certs/alipay/appPublicCert.crt"
  AlipayPublicKey = "certs/alipay/alipayPublicCert.crt"
  RootCert = "certs/alipay/alipayRootCert.crt"
  NotifyURL = "https://ai.r9it.com/api/payment/alipay/notify"
  ReturnURL = ""

[HuPiPayConfig]
  Enabled = false
  Name = "wechat"
  AppId = ""
  AppSecret = ""
  ApiURL = "https://api.xunhupay.com"
  NotifyURL = "https://ai.r9it.com/api/payment/hupipay/notify"
  ReturnURL = ""

[SmtpConfig]  # 注意，阿里云服务器禁用了25号端口，请使用 465 端口，并开启 TLS 连接
  UseTls = false
  Host = "smtp.163.com"
  Port = 25
  AppName = "talkme"
  From = "test@163.com"  # 发件邮箱人地址
  Password = ""  #邮箱 stmp 服务授权码

[JPayConfig]
  Enabled = false
  Name = "wechat"  # 请不要改动
  AppId = ""  # 商户 ID
  PrivateKey = "" # 秘钥
  ApiURL = "https://payjs.cn"
  NotifyURL = "https://ai.r9it.com/api/payment/payjs/notify"
  ReturnURL = ""
